services:
  - type: web
    name: MinaBot
    env: python
    plan: free
    pythonVersion: "3.11"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
